# Generated by Django 3.2.7 on 2022-11-03 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameter', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topfiletypes',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_files_types_color', to='parameter.colors', verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='topfiletypes',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_files_types_icon', to='parameter.icon', verbose_name='İcon'),
        ),
        migrations.AddField(
            model_name='filetypes',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_type_type', to='files.topfiletypes', verbose_name='Üst Dosya Tipi'),
        ),
        migrations.AddField(
            model_name='files',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_type', to='files.filetypes', verbose_name='Dosya Tipi'),
        ),
        migrations.AddField(
            model_name='files',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_user', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
